#!/bin/sh 

SERVERS=(monkeymolepanic mortalkombat motofrenzy lethalenforcers legionnaire lastresort knuckleheads kingofdragons)

for index in ${!SERVERS[*]}; do
  folder=$(expr $index + 1)
  ssh ekelly@${SERVERS[$index]}.ccs.neu.edu 'classes/networks/Cheating-Bittorent/testing/snark$folder/stuff'
done
